export const SET_AUTH = 'SET_AUTH';
export const REMOVE_AUTH = 'REMOVE_AUTH';

export const LTP_SET_FILTER = 'LTP_SET_FILTER';
export const WO_SET_FILTER = 'WO_SET_FILTER';
export const LTP_SET_ACTIVE_TAB = 'LTP_SET_ACTIVE_TAB';
export const LOAD_BLENDS = 'LOAD_BLENDS';
export const LOAD_IPGS = 'LOAD_IPGS';

export const PUSH_GLOBAL_NOTIFICATION = 'PUSH_GLOBAL_NOTIFICATION';
export const REMOVE_GLOBAL_NOTIFICATION = 'REMOVE_GLOBAL_NOTIFICATION';
export const LOAD_SCENARIO = 'LOAD_SCENARIO';
export const ON_TOGGLE_SHOW_BACKUP_SCENARIO = 'ON_TOGGLE_SHOW_BACKUP_SCENARIO';
export const SELECT_SCENARIO = 'SELECT_SCENARIO';
export const LOAD_SCENARIOS = 'LOAD_SCENARIOS';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const SAVE_SCENARIO = 'SAVE_SCENARIO';
export const OPTIMISE_SCENARIO = 'OPTIMISE_SCENARIO';
export const APPLY_SCENARIO_RESULTS_TO_MASTER = 'APPLY_SCENARIO_RESULTS_TO_MASTER';
export const CLEAR_SCENARIOS = 'CLEAR_SCENARIOS';
export const MARK_SCENARIO_OPTIMIZATION_ENDED = 'MARK_SCENARIO_OPTIMIZATION_ENDED';
export const MARK_SCENARIO_OPTIMIZATION_STARTED = 'MARK_SCENARIO_OPTIMIZATION_STARTED';
export const REPORT_SCENARIO_OPTIMIZATION_PROGRESS = 'REPORT_SCENARIO_OPTIMIZATION_PROGRESS';
export const MARK_SCENARIO_EVALUATION_ENDED = 'MARK_SCENARIO_EVALUATION_ENDED';
export const MARK_SCENARIO_EVALUATION_STARTED = 'MARK_SCENARIO_EVALUATION_STARTED';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_LOAD_SCENARIO_MODAL = 'SHOW_LOAD_SCENARIO_MODAL';
export const LOAD_SCENARIO_INTO_PANEL = 'LOAD_SCENARIO_INTO_PANEL';
export const LOADING = 'LOADING';
export const SHOW_SHARE_SETTINGS_MODAL = 'SHOW_SHARE_SETTINGS_MODAL';
export const SHOW_EDIT_SCENARIO_MODAL = 'SHOW_EDIT_SCENARIO_MODAL';
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL';
export const SHOW_APPLY_RESULTS_TO_MASTER_MODAL = 'SHOW_APPLY_RESULTS_TO_MASTER_MODAL';
export const SHOW_ASSIGN_WEIGHTING_TO_MASTER_MODAL = 'SHOW_ASSIGN_WEIGHTING_TO_MASTER_MODAL';
export const SHOW_MANAGE_WEIGHTING_PROFILES_MODAL = 'SHOW_MANAGE_WEIGHTING_PROFILES_MODAL';
export const SHOW_OPTIMISE_SCENARIO_MODAL = 'SHOW_OPTIMISE_SCENARIO_MODAL';
export const SHOW_OPTIMISATION_PROGRESS_BAR_MODAL = 'SHOW_OPTIMISATION_PROGRESS_BAR_MODAL';
export const SHOW_ADD_WEIGHTING_PROFILE_MODAL = 'SHOW_ADD_WEIGHTING_PROFILE_MODAL';
export const WEIGHTING_PROFILES_LOAD_LIST = 'WEIGHTING_PROFILES_LOAD_LIST';
export const WEIGHTING_PROFILES_ADD = 'WEIGHTING_PROFILES_ADD';
export const WEIGHTING_PROFILES_DELETE = 'WEIGHTING_PROFILES_DELETE';
export const WEIGHTING_PROFILES_DUPLICATE = 'WEIGHTING_PROFILES_DUPLICATE';
export const WEIGHTING_PROFILES_UPDATE_FACTORS = 'WEIGHTING_PROFILES_UPDATE_FACTORS';
export const WEIGHTING_SELECT_PROFILE = 'WEIGHTING_SELECT_PROFILE';
export const FACTOR_LOAD_BY_WEIGHTING_SET = 'FACTOR_LOAD_BY_WEIGHTING_SET';
export const CLEAR_WEIGHTING_PROFILES = 'CLEAR_WEIGHTING_PROFILES';
export const ASSIGN_WEIGHTINGS_SET_TO_MASTER = 'ASSIGN_WEIGHTINGS_SET_TO_MASTER';

export const BOTTLING_SET_SIDEBAR_FILTER = 'BOTTLING_SET_SIDEBAR_FILTER';

export const BOTTLING_LOAD_LINES = 'BOTTLING_LOAD_LINES';
export const BOTTLING_LOAD_AVAILABLE_LINES = 'BOTTLING_LOAD_AVAILABLE_LINES';
export const BOTTLING_CLEAR_LINES = 'BOTTLING_CLEAR_LINES';

export const BOTTLING_BRANCH_FILTER_LOAD_OPTIONS = 'BOTTLING_BRANCH_FILTER_LOAD_OPTIONS';
export const LTP_BRANCH_FILTER_LOAD_OPTIONS = 'LTP_BRANCH_FILTER_LOAD_OPTIONS';
export const LTP_IPG_FILTER_LOAD_OPTIONS = 'LTP_IPG_FILTER_LOAD_OPTIONS';
export const LTP_BLEND_FILTER_LOAD_OPTIONS = 'LTP_BLEND_FILTER_LOAD_OPTIONS';
export const LTP_SUPPLIER_FILTER_LOAD_OPTIONS = 'LTP_SUPPLIER_FILTER_LOAD_OPTIONS';
export const FINANCIAL_CALENDAR_LOAD_NEXT_PLAN_CALENDAR_WINDOW = 'FINANCIAL_CALENDAR_LOAD_NEXT_PLAN_CALENDAR_WINDOW';

export const LTP_BLEND_WINE_PO_LOAD_STATUS = 'LTP_BLEND_WINE_PO_LOAD_STATUS';
export const LTP_BLEND_WINE_PO_CLEAN_STATUS = 'LTP_BLEND_WINE_PO_CLEAN_STATUS';
export const LTP_BLEND_WINE_SET_EMPTY = 'LTP_BLEND_WINE_SET_EMPTY';

export const LTP_OPTIMIZATION_LOAD_LOG_MESSAGE = 'LTP_OPTIMIZATION_LOAD_LOG_MESSAGE';
export const LTP_OPTIMIZATION_CLEAN_LOG_MESSAGE = 'LTP_OPTIMIZATION_CLEAN_LOG_MESSAGE';

export const LTP_BOTTLING_WO_LOAD_STATUS = 'LTP_BOTTLING_WO_LOAD_STATUS';
export const LTP_BOTTLING_WO_CLEAN_STATUS = 'LTP_BOTTLING_WO_CLEAN_STATUS';

export const LTP_IMPORTED_SKU_INFORMATION = 'LTP_IMPORTED_SKU_INFORMATION';

export const LTP_SF_WO_LOAD_STATUS = 'LTP_SF_WO_LOAD_STATUS';
export const LTP_SF_WO_CLEAN_STATUS = 'LTP_SF_WO_CLEAN_STATUS';

export const LTP_TRANSFER_WO_LOAD_STATUS = 'LTP_TRANSFER_WO_LOAD_STATUS';
export const LTP_TRANSFER_WO_CLEAN_STATUS = 'LTP_TRANSFER_WO_CLEAN_STATUS';
export const LTP_CO_PACKING_WO_LOAD_STATUS = 'LTP_CO_PACKING_WO_LOAD_STATUS';
export const LTP_CO_PACKING_WO_CLEAN_STATUS = 'LTP_CO_PACKING_WO_CLEAN_STATUS';

export const LTP_PURCHASE_ORDER_LOAD_STATUS = 'LTP_PURCHASE_ORDER_LOAD_STATUS';
export const LTP_PURCHASE_ORDER_CLEAN_STATUS = 'LTP_PURCHASE_ORDER_CLEAN_STATUS';

export const RESPONSIVE_FIXED_DATA_TABLE_SEARCH_APPLY = 'RESPONSIVE_FIXED_DATA_TABLE_SEARCH_APPLY';
export const RESPONSIVE_FIXED_DATA_TABLE_SEARCH_TOGGLE = 'RESPONSIVE_FIXED_DATA_TABLE_SEARCH_TOGGLE';
export const RESPONSIVE_FIXED_DATA_TABLE_FOCUS = 'RESPONSIVE_FIXED_DATA_TABLE_FOCUS';
export const RESPONSIVE_FIXED_DATA_TABLE_BLUR = 'RESPONSIVE_FIXED_DATA_TABLE_BLUR';

export const LTP_SET_EXPAND_ROW = 'LTP_SET_EXPAND_ROW';
export const LTP_RESET_EXPAND_ROW = 'LTP_RESET_EXPAND_ROW';
export const LTP_VIEW_SELECT = 'LTP_VIEW_SELECT';
export const LTP_LOAD_ALERTS = 'LTP_LOAD_ALERTS';
export const LTP_CLEAN_ALERTS = 'LTP_CLEAN_ALERTS';
export const BOTTLING_LTP_SET_EXPAND_ROW = 'BOTTLING_LTP_SET_EXPAND_ROW';
export const BOTTLING_LTP_RESET_EXPAND_ROW = 'BOTTLING_LTP_RESET_EXPAND_ROW';
export const OW_LTP_SET_EXPAND_ROW = 'OW_LTP_SET_EXPAND_ROW';
export const OW_LTP_RESET_EXPAND_ROW = 'OW_LTP_RESET_EXPAND_ROW';

export const SCENARIO_LOAD_MASTER = 'SCENARIO_LOAD_MASTER';

export const CURRENT_STATUS_CHANGE_FILTER = 'CURRENT_STATUS_CHANGE_FILTER';

export const BRANCH_LINE_WORK_PLANNER_UPDATE_STATE = 'BRANCH_LINE_WORK_PLANNER_UPDATE_STATE';

export const LOADING_USER_DETAILS = 'LOADING_USER_DETAILS';
export const LOAD_USER_DETAILS = 'LOAD_USER_DETAILS';
